"""Self-contained HTML dashboard. Opens in any browser; Chart.js from CDN."""
from __future__ import annotations
import json
from collections import Counter


def build_dashboard(results: dict, out_path: str, title: str = "Seykota Bot — Backtest"):
    m = results["metrics"]
    trades = results["trades"]
    eq = results["equity_curve"]

    red = [t for t in trades if t["pnl"] < 0]
    red_reasons = Counter(t.get("red_reason", "UNSPEC") for t in red)
    by_epic = {}
    for t in trades:
        by_epic.setdefault(t["epic"], 0.0)
        by_epic[t["epic"]] += t["pnl"]

    def card(label, value, good=None):
        cls = "" if good is None else ("pos" if good else "neg")
        return f'<div class="card"><div class="lbl">{label}</div><div class="val {cls}">{value}</div></div>'

    pf = m.get("profit_factor")
    cards = "".join([
        card("Total Return", f'{m["total_return_pct"]}%', m["total_return_pct"] > 0),
        card("CAGR", f'{m["cagr_pct"]}%', m["cagr_pct"] > 0),
        card("Max Drawdown", f'{m["max_drawdown_pct"]}%', False),
        card("Sharpe", m["sharpe"], m["sharpe"] > 1),
        card("Sortino", m["sortino"], m["sortino"] > 1),
        card("MAR / Calmar", m["mar_calmar"], m["mar_calmar"] > 0.5),
        card("Trades", m["num_trades"]),
        card("Win Rate", f'{m["win_rate_pct"]}%'),
        card("Profit Factor", pf if pf is not None else "∞", (pf or 9) > 1),
        card("Payoff Ratio", m["payoff_ratio"], m["payoff_ratio"] > 1),
        card("Avg Win", f'{m["avg_win"]:,}'),
        card("Avg Loss", f'{m["avg_loss"]:,}'),
        card("Expectancy/Trade", f'{m["expectancy_per_trade"]:,}', m["expectancy_per_trade"] > 0),
        card("End Equity", f'{m["end_equity"]:,}'),
    ])

    rows = ""
    for t in sorted(trades, key=lambda x: x["exit_date"]):
        cls = "win" if t["pnl"] >= 0 else "loss"
        d = "LONG" if t["direction"] > 0 else "SHORT"
        rows += (f'<tr class="{cls}"><td>{t["exit_date"]}</td><td>{t["epic"]}</td><td>{d}</td>'
                 f'<td>{t["entry_price"]}</td><td>{t["exit_price"]}</td><td>{t["bars_held"]}</td>'
                 f'<td>{t["pnl"]:,}</td><td>{t["exit_reason"]}</td><td>{t.get("red_reason","")}</td></tr>')

    reason_rows = "".join(
        f'<tr><td>{k}</td><td>{v}</td></tr>' for k, v in red_reasons.most_common())
    epic_rows = "".join(
        f'<tr><td>{k}</td><td class="{"pos" if v>=0 else "neg"}">{round(v,2):,}</td></tr>'
        for k, v in sorted(by_epic.items(), key=lambda kv: kv[1], reverse=True))

    payload = json.dumps({
        "labels": [e["date"] for e in eq],
        "equity": [e["equity"] for e in eq],
        "drawdown": [round(e["drawdown"] * 100, 2) for e in eq],
        "heat": [round(e["heat"] * 100, 2) for e in eq],
    })

    html = f"""<!doctype html><html><head><meta charset="utf-8">
<title>{title}</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<style>
:root{{color-scheme:dark}}
body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;background:#0f1115;color:#e6e8ec}}
.wrap{{max-width:1200px;margin:0 auto;padding:24px}}
h1{{font-size:20px;margin:0 0 4px}} .sub{{color:#9aa0aa;font-size:13px;margin-bottom:20px}}
.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-bottom:24px}}
.card{{background:#171a21;border:1px solid #232733;border-radius:10px;padding:12px 14px}}
.lbl{{color:#9aa0aa;font-size:11px;text-transform:uppercase;letter-spacing:.04em}}
.val{{font-size:20px;font-weight:600;margin-top:4px}} .pos{{color:#4ade80}} .neg{{color:#f87171}}
.panel{{background:#171a21;border:1px solid #232733;border-radius:10px;padding:16px;margin-bottom:24px}}
h2{{font-size:14px;margin:0 0 12px;color:#cbd2dc}}
table{{width:100%;border-collapse:collapse;font-size:12px}}
th,td{{text-align:left;padding:6px 8px;border-bottom:1px solid #232733}}
th{{color:#9aa0aa;font-weight:500}}
tr.loss td{{background:rgba(248,113,113,.07)}} tr.win td{{background:rgba(74,222,128,.05)}}
.two{{display:grid;grid-template-columns:1fr 1fr;gap:24px}}
@media(max-width:800px){{.two{{grid-template-columns:1fr}}}}
.note{{color:#9aa0aa;font-size:12px}}
</style></head><body><div class="wrap">
<h1>{title}</h1>
<div class="sub">Seykota-style trend following · generated by the bot. Metrics are net of modeled spread/financing.</div>
<div class="grid">{cards}</div>
<div class="panel"><h2>Equity curve</h2><canvas id="eq" height="90"></canvas></div>
<div class="panel"><h2>Drawdown (%) & portfolio heat (%)</h2><canvas id="dd" height="80"></canvas></div>
<div class="two">
  <div class="panel"><h2>Why losing trades went RED</h2>
    <table><tr><th>Reason</th><th>Count</th></tr>{reason_rows or '<tr><td colspan=2>No losing trades</td></tr>'}</table>
    <p class="note">WHIPSAW & RULE_OK_LOSS are expected costs of trend following — one big winner pays for many.</p>
  </div>
  <div class="panel"><h2>P&amp;L by instrument</h2>
    <table><tr><th>Instrument</th><th>Net P&amp;L</th></tr>{epic_rows}</table>
  </div>
</div>
<div class="panel"><h2>All trades</h2>
<table><tr><th>Exit date</th><th>Instrument</th><th>Side</th><th>Entry</th><th>Exit</th><th>Bars</th><th>P&amp;L</th><th>Exit</th><th>Red reason</th></tr>
{rows}</table></div>
</div>
<script>
const d={payload};
new Chart(document.getElementById('eq'),{{type:'line',data:{{labels:d.labels,datasets:[{{label:'Equity',data:d.equity,borderColor:'#4ade80',backgroundColor:'rgba(74,222,128,.08)',fill:true,pointRadius:0,borderWidth:1.5}}]}},options:{{plugins:{{legend:{{display:false}}}},scales:{{x:{{ticks:{{maxTicksLimit:10,color:'#9aa0aa'}},grid:{{color:'#1c2029'}}}},y:{{ticks:{{color:'#9aa0aa'}},grid:{{color:'#1c2029'}}}}}}}}}});
new Chart(document.getElementById('dd'),{{type:'line',data:{{labels:d.labels,datasets:[{{label:'Drawdown %',data:d.drawdown,borderColor:'#f87171',backgroundColor:'rgba(248,113,113,.12)',fill:true,pointRadius:0,borderWidth:1.2}},{{label:'Heat %',data:d.heat,borderColor:'#60a5fa',pointRadius:0,borderWidth:1,fill:false}}]}},options:{{plugins:{{legend:{{labels:{{color:'#9aa0aa'}}}}}},scales:{{x:{{ticks:{{maxTicksLimit:10,color:'#9aa0aa'}},grid:{{color:'#1c2029'}}}},y:{{ticks:{{color:'#9aa0aa'}},grid:{{color:'#1c2029'}}}}}}}}}});
</script></body></html>"""
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    return out_path
